name: Deploy to Streamlit Cloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test imports
      run: |
        python -c "import streamlit, yfinance, pandas, numpy, scipy, plotly; print('All imports successful')"
    
    - name: Test app structure
      run: |
        python -c "
        import sys
        sys.path.append('.')
        from options_calculator import calculator
        from data_fetcher import data_fetcher
        from utils import validate_stock_symbol
        print('All modules imported successfully')
        "

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Deploy to Streamlit Cloud
      run: |
        echo "Deployment will be handled by Streamlit Cloud automatically"
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref_name }}"
