# Streamlit Cloud 配置文件
# 这个文件用于存储敏感信息，在本地开发时使用

[general]
# 应用配置
app_name = "美股期权分析策略平台"
version = "1.0.0"

# 数据源配置
data_source = "Yahoo Finance"
update_frequency = "实时"

# 风险提示
risk_warning = "期权交易存在高风险，本平台仅供参考，不构成投资建议"
